"use client";

import { useState, useEffect } from "react";
import { Save, Store, Phone, Mail, MapPin, Megaphone, Eye } from "lucide-react";
import { getSettings, updateSettings } from "@/actions/index";
import { toast } from "sonner";

export default function AdminSettingsPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [formData, setFormData] = useState({
    storeName: "Tayna Xavier Boutique",
    whatsapp: "",
    instagram: "",
    email: "",
    address: "",
    topBarText: "",
    freeShippingMin: 299,
    installments: 6,
  });

  useEffect(() => {
    async function loadData() {
      const res = await getSettings();
      if (res.success && res.data) {
        setFormData({
          storeName: res.data.storeName || "",
          whatsapp: res.data.whatsapp || "",
          instagram: res.data.instagram || "",
          email: res.data.email || "",
          address: res.data.address || "",
          topBarText: res.data.topBarText || "Frete grátis para compras acima de R$ 299 ✦ Parcele em até 6x sem juros",
          freeShippingMin: (res.data as any).freeShippingMin ?? 299,
          installments: (res.data as any).installments ?? 6,
        });
      }
      setLoading(false);
    }
    loadData();
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === "number" ? (value === "" ? "" : Number(value)) : value,
    }));
  };

  // I - Live preview: auto-build topBarText from freeShippingMin + installments
  const autoGeneratedText = `Frete grátis para compras acima de R$ ${formData.freeShippingMin} ✦ Parcele em até ${formData.installments}x sem juros`;

  const handleSave = async () => {
    setSaving(true);
    const res = await updateSettings(formData);
    if (res.success) {
      toast.success("Configurações salvas com sucesso!");
    } else {
      toast.error(res.message || "Erro ao salvar configurações.");
    }
    setSaving(false);
  };

  if (loading) {
    return <div className="flex justify-center items-center h-64"><p className="text-muted-foreground">Carregando configurações...</p></div>;
  }

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h1 className="text-2xl font-heading font-bold">Configurações</h1>
        <p className="text-sm text-muted-foreground">Configurações gerais da loja</p>
      </div>
      <div className="space-y-6">

        {/* Store Info */}
        <div className="p-6 bg-card border border-border rounded-2xl space-y-4">
          <h3 className="font-heading text-sm font-semibold flex items-center gap-2"><Store className="w-4 h-4 text-brand" /> Informações da Loja</h3>
          <div>
            <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Nome da Loja</label>
            <input type="text" name="storeName" value={formData.storeName} onChange={handleChange}
              className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
          </div>
        </div>

        {/* G + I - Announcement Bar */}
        <div className="p-6 bg-card border border-border rounded-2xl space-y-4">
          <h3 className="font-heading text-sm font-semibold flex items-center gap-2"><Megaphone className="w-4 h-4 text-brand" /> Barra de Anúncios do Topo</h3>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Frete Grátis Acima de (R$)</label>
              <input type="number" name="freeShippingMin" value={formData.freeShippingMin} onChange={handleChange} min={0}
                className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
            </div>
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Máximo de Parcelas (x)</label>
              <input type="number" name="installments" value={formData.installments} onChange={handleChange} min={1} max={24}
                className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
            </div>
          </div>

          <div>
            <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Texto Personalizado (substitui os campos acima se preenchido)</label>
            <input type="text" name="topBarText" value={formData.topBarText} onChange={handleChange}
              placeholder="Ex: Frete grátis para compras acima de R$ 299..."
              className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
          </div>

          {/* I - Live Preview */}
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Eye className="w-3.5 h-3.5 text-muted-foreground" />
              <span className="text-xs font-medium text-muted-foreground">Pré-visualização em tempo real</span>
            </div>
            <div className="bg-primary text-primary-foreground text-center py-2.5 px-4 text-xs tracking-[0.2em] uppercase font-medium rounded-xl">
              {formData.topBarText?.trim() || autoGeneratedText}
            </div>
          </div>
        </div>

        {/* Contact */}
        <div className="p-6 bg-card border border-border rounded-2xl space-y-4">
          <h3 className="font-heading text-sm font-semibold flex items-center gap-2"><Phone className="w-4 h-4 text-brand" /> Contato</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1.5 block">WhatsApp</label>
              <input type="text" name="whatsapp" value={formData.whatsapp} onChange={handleChange} placeholder="(00) 00000-0000"
                className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
            </div>
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1.5 block">E-mail</label>
              <input type="email" name="email" value={formData.email} onChange={handleChange} placeholder="contato@loja.com"
                className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
            </div>
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Instagram</label>
              <input type="text" name="instagram" value={formData.instagram} onChange={handleChange} placeholder="@taynaxavier_boutique"
                className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
            </div>
            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1.5 block">Endereço</label>
              <input type="text" name="address" value={formData.address} onChange={handleChange} placeholder="Endereço da loja"
                className="w-full px-4 py-3 border border-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand/30" />
            </div>
          </div>
        </div>

        <button onClick={handleSave} disabled={saving} className="flex items-center gap-2 px-6 py-3 bg-brand text-white rounded-xl text-sm font-medium hover:bg-brand/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed">
          <Save className="w-4 h-4" /> {saving ? "Salvando..." : "Salvar Alterações"}
        </button>
      </div>
    </div>
  );
}
